language: node_js

node_js:
  - '10'
  - '8'

branches:
  only:
    - master

install:
  - travis_retry npm install

# script:
#   - npm test
#   - npm run coveralls

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npx semantic-release
